### ISSUE TITLE
Thanks a lot for the project,but I have some problems 

### ISSUE THREAD

**Issue by chenglong19029001** [jkjung-avt/keras_imagenet#2]
Sorry to trouble you, when I train a model likes resnet50 in your project. I use the trained model to predict the raw image and use the keras processing function.The acc is 0, So how can I make the model work? And I also scale the image to [0,1],but the acc is closely to 0.

**Comment by jkjung-avt** [comment]
I have created a [predict_image.py](https://github.com/jkjung-avt/keras_imagenet/blob/master/predict_image.py) script to demonstrate how to predict an image with a trained model.

Please note that I fix this [class id off by one bug](https://github.com/jkjung-avt/keras_imagenet/commit/12fd478ef307fc54453537dc2ee45439f56c7b0b) just about 2 weeks ago.  So if you are to train an ImageNet classification model, you probably need to check out the latest code and re-do the training.

I'm providing a googlenet_bn model trained by myself.  You could download it and verify the result.  Refer to README.md.
