### ISSUE TITLE
How to train on Custom Data

### ISSUE THREAD

**Issue by kmanojkkmr** [jkjung-avt/keras_imagenet#4]
Hello Team,

I would like to train this script on my own dataset to predict tables from images. Could you please provide me the steps on how to train it on my dataset.

Also, I am using Tensorflow 2.2.0 and CPU system.

Thank you in advance. :)

**Comment by jkjung-avt** [comment]
Sorry, there's no easy answer to this.  I think the code for preparing tfrecord files would require some major modifications if you are to use your own dataset...
